from __future__ import annotations

from pathlib import Path

import pytest

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture
def clean_statement_path() -> Path:
    return FIXTURES / "hdfc_april_2025.csv"


@pytest.fixture
def dropped_row_path() -> Path:
    """Same statement with the Netflix row (Rs 649.00) deleted.

    This is the realistic parser failure: a row swallowed by a wrapped
    narration or a page break.
    """
    return FIXTURES / "hdfc_april_2025_dropped_row.csv"


@pytest.fixture
def signed_amount_path() -> Path:
    return FIXTURES / "icici_may_2025_signed.csv"


@pytest.fixture
def pdf_path() -> Path:
    """The same statement as `clean_statement_path`, rendered as a ruled PDF."""
    return FIXTURES / "hdfc_april_2025.pdf"


@pytest.fixture
def locked_pdf_path() -> Path:
    return FIXTURES / "hdfc_april_2025_locked.pdf"


@pytest.fixture
def spreadsheet_path() -> Path:
    """The same statement again, as a workbook full of real-world quirks."""
    return FIXTURES / "hdfc_april_2025.xls"


@pytest.fixture
def hdfc_aug_path() -> Path:
    """One side of an inter-account transfer: Rs 25,000 out to ICICI."""
    return FIXTURES / "hdfc_aug_2025.csv"


@pytest.fixture
def icici_aug_path() -> Path:
    """The other side: the same Rs 25,000 arriving."""
    return FIXTURES / "icici_aug_2025.csv"


@pytest.fixture
def patterns_path() -> Path:
    """Five months containing one of each thing worth finding.

    Generated by scripts/make_patterns_fixture.py.
    """
    return FIXTURES / "hdfc_jan_may_2025.csv"


@pytest.fixture
def july_bank_path() -> Path:
    """A bank statement whose CRED debit settles the card fixture's payment."""
    return FIXTURES / "hdfc_july_2025.csv"


@pytest.fixture
def card_path() -> Path:
    """A credit-card statement: summary box, no running balance, Cr suffixes."""
    return FIXTURES / "hdfc_card_july_2025.csv"


@pytest.fixture
def fixture_password() -> str:
    """Unlocks a synthetic fixture and nothing else."""
    return "test1234"


@pytest.fixture
def icici_currency_headers_path() -> Path:
    """ICICI's two departures from the HDFC layout, in one file.

    Money columns labelled with the currency and no space before the bracket
    (``Withdrawal Amount(INR)``), and an explicit ``0.00`` in the unused side
    of the debit/credit pair where HDFC leaves the cell empty. Either one alone
    stopped the file parsing at all.
    """
    return FIXTURES / "icici_currency_headers.csv"


@pytest.fixture
def axis_stated_totals_path() -> Path:
    """Axis's layout, including the ``TRANSACTION TOTAL`` row it prints.

    Both endpoints are derived, so the chain and totals checks are as weak as
    they get -- which is exactly the statement where the bank's own column
    totals are worth having.
    """
    return FIXTURES / "axis_stated_totals.csv"


@pytest.fixture
def axis_stated_totals_dropped_path() -> Path:
    """The same statement with its *last* transaction row lost.

    The case both other checks pass: the closing balance goes missing with the
    row, so the chain stays consistent and the totals still add up.
    """
    return FIXTURES / "axis_stated_totals_dropped.csv"


@pytest.fixture
def unruled_pdf_path() -> Path:
    """The ruled PDF fixture with its grid removed and nothing else changed.

    Real bank PDFs draw no ruling: three third-party samples (two ICICI, one
    HDFC, from separate projects) all report zero lines, zero rects and zero
    edges. Built by scripts/make_unruled_pdf_fixture.py.
    """
    return FIXTURES / "hdfc_april_2025_unruled.pdf"


@pytest.fixture
def wrapped_pdf_path() -> Path:
    """An ICICI-shaped PDF whose narrations wrap around the dated line.

    The structure that actually defeats the parser on real statements.
    """
    return FIXTURES / "icici_july_2026_wrapped.pdf"
