"""Phase 3: refunds, duplicates and subscriptions.

Assertions run against `hdfc_jan_may_2025.csv`, which is generated by
`scripts/make_patterns_fixture.py` with computed running balances -- it
reconciles by construction, so a hand-arithmetic slip cannot quietly invalidate
anything built on it.
"""

from __future__ import annotations

from datetime import date, timedelta
from pathlib import Path

import pytest

from moneytrail import Direction, Statement, Transaction, parse_statement, reconcile
from moneytrail.cli import main
from moneytrail.patterns import find_duplicates, find_recurring, find_refunds


@pytest.fixture
def ledger(patterns_path):
    return parse_statement(patterns_path)


def _statement(entries) -> Statement:
    """Build a ledger straight from (day-offset, narration, direction, amount)."""
    start = date(2025, 1, 1)
    transactions = tuple(
        Transaction(
            row=index,
            date=start + timedelta(days=offset),
            narration=narration,
            direction=direction,
            amount=amount,
        )
        for index, (offset, narration, direction, amount) in enumerate(entries, start=1)
    )
    return Statement(
        source=Path("synthetic"),
        bank="test",
        account_hint="",
        opening_balance=0,
        closing_balance=0,
        transactions=transactions,
    )


def test_the_fixture_reconciles(ledger):
    assert reconcile(ledger).ok


class TestRecurring:
    def test_finds_subscriptions_and_bills(self, ledger):
        found = {item.merchant: item for item in find_recurring(ledger)}

        assert "Netflix" in found
        assert "Spotify" in found
        # Not only subscriptions: rent is a cadence too.
        assert any("Rent" in name for name in found)

    def test_measures_the_cadence_rather_than_assuming_it(self, ledger):
        netflix = next(i for i in find_recurring(ledger) if i.merchant == "Netflix")

        assert netflix.cadence == "monthly"
        assert netflix.typical_amount == 64_900
        assert len(netflix.occurrences) == 5
        assert netflix.annualised == 789_617  # 649.00 x 365/30

    def test_a_cancelled_subscription_is_marked_stopped(self, ledger):
        spotify = next(i for i in find_recurring(ledger) if i.merchant == "Spotify")

        assert not spotify.active
        assert spotify.last_seen == date(2025, 3, 7)

    def test_income_is_not_a_recurring_charge(self, ledger):
        # The salary credit arrives every month like clockwork and is not a bill.
        assert not any("Acme" in i.merchant for i in find_recurring(ledger))

    def test_ordered_by_what_it_costs_a_year(self, ledger):
        annual = [item.annualised for item in find_recurring(ledger)]

        assert annual == sorted(annual, reverse=True)

    def test_two_charges_are_not_a_cadence(self):
        ledger = _statement(
            [(0, "UPI-NETFLIXINDIA-NETFLIX@ICICI", Direction.DEBIT, 64_900),
             (30, "UPI-NETFLIXINDIA-NETFLIX@ICICI", Direction.DEBIT, 64_900)]
        )

        assert find_recurring(ledger) == []

    def test_irregular_gaps_are_not_a_cadence(self):
        # Three charges, but at 5, 60 and 90 days: a habit, not a subscription.
        ledger = _statement(
            [(offset, "UPI-SWIGGY-SWIGGY@YBL", Direction.DEBIT, 45_000)
             for offset in (0, 5, 65, 155)]
        )

        assert find_recurring(ledger) == []

    def test_wildly_varying_amounts_are_not_a_cadence(self):
        ledger = _statement(
            [(0, "UPI-SWIGGY-SWIGGY@YBL", Direction.DEBIT, 20_000),
             (30, "UPI-SWIGGY-SWIGGY@YBL", Direction.DEBIT, 90_000),
             (60, "UPI-SWIGGY-SWIGGY@YBL", Direction.DEBIT, 150_000)]
        )

        assert find_recurring(ledger) == []


class TestDuplicates:
    def test_finds_the_same_charge_twice_in_a_day(self, ledger):
        found = {dup.merchant: dup for dup in find_duplicates(ledger)}

        assert set(found) == {"Swiggy", "Amazon"}
        assert found["Swiggy"].count == 2
        assert found["Swiggy"].span_days == 0

    def test_a_refunded_duplicate_leaves_nothing_outstanding(self, ledger):
        amazon = next(d for d in find_duplicates(ledger) if d.merchant == "Amazon")

        assert amazon.refunded == 1
        assert amazon.exposure == 0

    def test_an_unrefunded_duplicate_is_money_still_out(self, ledger):
        swiggy = next(d for d in find_duplicates(ledger) if d.merchant == "Swiggy")

        assert swiggy.refunded == 0
        assert swiggy.exposure == 45_000

    def test_ordered_by_what_is_still_outstanding(self, ledger):
        exposures = [dup.exposure for dup in find_duplicates(ledger)]

        assert exposures == sorted(exposures, reverse=True)

    def test_charges_far_apart_are_not_duplicates(self, ledger):
        # Monthly Netflix is the same merchant and amount every time, and must
        # not be mistaken for a double charge.
        assert not any(d.merchant == "Netflix" for d in find_duplicates(ledger))


class TestRefunds:
    def test_matches_a_credit_back_to_its_charge(self, ledger):
        loops = {loop.merchant: loop for loop in find_refunds(ledger)}

        assert set(loops) == {"Amazon", "Myntra"}
        assert loops["Myntra"].amount == 249_900
        assert loops["Myntra"].lag_days == 12
        assert loops["Myntra"].charge.date == date(2025, 4, 15)

    def test_one_credit_cannot_close_two_charges(self, ledger):
        # Amazon was charged twice and refunded once.
        amazon = [loop for loop in find_refunds(ledger) if loop.merchant == "Amazon"]

        assert len(amazon) == 1

    def test_a_credit_before_its_charge_is_not_a_refund(self):
        ledger = _statement(
            [(0, "UPI-MYNTRADESIGNS-MYNTRA@AXISBANK", Direction.CREDIT, 249_900),
             (10, "UPI-MYNTRADESIGNS-MYNTRA@AXISBANK", Direction.DEBIT, 249_900)]
        )

        assert find_refunds(ledger) == []

    def test_a_credit_long_after_the_charge_is_not_a_refund(self):
        entries = [
            (0, "UPI-MYNTRADESIGNS-MYNTRA@AXISBANK", Direction.DEBIT, 249_900),
            (200, "UPI-MYNTRADESIGNS-MYNTRA@AXISBANK", Direction.CREDIT, 249_900),
        ]

        assert find_refunds(_statement(entries)) == []
        assert len(find_refunds(_statement(entries), window_days=365)) == 1


class TestCommand:
    def test_reports_all_three(self, patterns_path, capsys):
        assert main(["review", str(patterns_path)]) == 0

        out = capsys.readouterr().out
        assert "recurring charges" in out
        assert "possible duplicate charges" in out
        assert "refunds that arrived" in out
        assert "Spotify" in out and "stopped" in out

    def test_states_what_it_cannot_detect(self, patterns_path, capsys):
        main(["review", str(patterns_path)])

        assert "cannot be detected" in capsys.readouterr().out
