"""PDF is the format banks actually send, so it gets the same gate as CSV.

Fixtures are generated by ``scripts/make_pdf_fixtures.py`` from the same seven
transactions as the CSV fixture, which lets the two formats be compared
directly: if the PDF grid recovery drops or mangles anything, the ledgers
diverge.
"""

from __future__ import annotations

import pytest

from moneytrail import parse_statement, reconcile
from moneytrail.parsers import PasswordRequired, UnparseableStatement


def test_pdf_reconciles_to_the_paisa(pdf_path):
    result = reconcile(parse_statement(pdf_path))

    assert result.ok, result.report()
    assert result.credits == 8_749_900
    assert result.debits == 3_656_000


def test_pdf_and_csv_produce_the_same_ledger(pdf_path, clean_statement_path):
    from_pdf = parse_statement(pdf_path)
    from_csv = parse_statement(clean_statement_path)

    assert from_pdf.opening_balance == from_csv.opening_balance
    assert from_pdf.closing_balance == from_csv.closing_balance
    assert from_pdf.account_hint == from_csv.account_hint
    assert from_pdf.bank == from_csv.bank

    # Row and page locators are format-specific; everything else must match.
    def ledger(statement):
        return [
            (t.date, t.narration, t.direction, t.amount, t.balance, t.value_date)
            for t in statement.transactions
        ]

    assert ledger(from_pdf) == ledger(from_csv)


def test_pdf_rows_carry_a_page_locator(pdf_path):
    statement = parse_statement(pdf_path)

    assert all(t.page == 1 for t in statement.transactions)
    assert [t.row for t in statement.transactions] == list(range(3, 10))


def test_balance_marker_rows_are_not_transactions(pdf_path):
    statement = parse_statement(pdf_path)

    assert len(statement.transactions) == 7
    assert all("BALANCE" not in t.narration for t in statement.transactions)


def test_encryption_is_read_from_the_file_not_from_an_exception(
    locked_pdf_path, pdf_path
):
    # CI caught this: pdfminer's password error moved between versions and
    # arrives with an empty message on Linux, so a locked statement was
    # reported as simply unreadable there while working on Windows.
    from moneytrail.parsers.pdf_statement import is_encrypted

    assert is_encrypted(locked_pdf_path)
    assert not is_encrypted(pdf_path)


def test_locked_pdf_asks_for_a_password(locked_pdf_path):
    with pytest.raises(PasswordRequired) as caught:
        parse_statement(locked_pdf_path)

    assert caught.value.wrong is False
    assert "password required" in str(caught.value)


def test_wrong_password_says_it_is_wrong(locked_pdf_path):
    with pytest.raises(PasswordRequired) as caught:
        parse_statement(locked_pdf_path, password="not-the-password")

    assert caught.value.wrong is True
    assert "password is incorrect" in str(caught.value)


def test_right_password_opens_it(locked_pdf_path, fixture_password, pdf_path):
    unlocked = parse_statement(locked_pdf_path, password=fixture_password)

    assert reconcile(unlocked).ok
    assert len(unlocked.transactions) == len(parse_statement(pdf_path).transactions)


def test_a_pdf_with_no_table_is_rejected_rather_than_guessed_at(tmp_path):
    from reportlab.pdfgen.canvas import Canvas

    target = tmp_path / "letter.pdf"
    canvas = Canvas(str(target))
    canvas.drawString(72, 720, "Dear customer, thank you for banking with us.")
    canvas.save()

    # A letter has text on it, so the message must point at the missing table
    # rather than at OCR -- there is nothing to scan-convert here.
    with pytest.raises(Exception, match="no transaction table was recognised"):
        parse_statement(target)


# --- PDFs this project did not draw itself ----------------------------------


def test_an_unruled_pdf_loses_the_chain_check(unruled_pdf_path):
    """The quiet failure, and the more dangerous of the two.

    Strip the ruling and the transactions are still found -- but the
    running-balance column is not, so the chain check silently stops running
    and the statement still reports RECONCILED on half the evidence. Every real
    bank PDF looked at so far is unruled, so this is the normal case, not the
    exotic one.
    """
    statement = parse_statement(unruled_pdf_path)
    result = reconcile(statement)

    assert len(statement.transactions) == 7
    assert result.ok
    assert statement.rows_with_balance == 0
    assert not result.chain_checked  # the fault localiser is gone


def test_a_ruled_pdf_keeps_it(pdf_path):
    """The same statement, ruled: every row carries its balance."""
    statement = parse_statement(pdf_path)

    assert statement.rows_with_balance == 7
    assert reconcile(statement).chain_checked


@pytest.mark.xfail(
    reason=(
        "narrations wrapping above and below the dated line mean a row is not "
        "a line, which column-splitting cannot fix at any threshold. Rows have "
        "to be assembled by finding the dated line and absorbing its "
        "neighbours. This is the real ICICI layout and the blocker for PDFs."
    ),
    strict=True,
)
def test_a_wrapped_narration_pdf_parses(wrapped_pdf_path):
    statement = parse_statement(wrapped_pdf_path)

    assert len(statement.transactions) == 3
    assert reconcile(statement).ok


def test_the_failure_says_which_failure_it_was(wrapped_pdf_path):
    """A page with text on it was read fine; recognising a table is what failed.

    Blaming OCR sends someone off to scan-convert a document that was never
    scanned, which is a long way to walk for no reason.
    """
    with pytest.raises(UnparseableStatement) as caught:
        parse_statement(wrapped_pdf_path)

    message = str(caught.value)
    assert "no ruling lines" in message
    assert "OCR" not in message
