"""Generate the spreadsheet fixture.

Modelled on the quirks of a real HDFC export, all of which broke the parser the
first time it met one:

- the file is OOXML but named ``.xls``
- rows of asterisks used as section dividers
- amounts masked with ``******``
- a "STATEMENT SUMMARY" block at the foot, stating the endpoints as a row of
  labels above a row of values

The transactions are the same seven as the CSV and PDF fixtures, so all three
formats can be asserted to produce one identical ledger.

    python scripts/make_xlsx_fixtures.py
"""

from __future__ import annotations

from pathlib import Path

from openpyxl import Workbook

FIXTURES = Path(__file__).resolve().parent.parent / "tests" / "fixtures"

HEADER = [
    "Date", "Narration", "Chq./Ref.No.", "Value Dt",
    "Withdrawal Amt.", "Deposit Amt.", "Closing Balance",
]

TRANSACTIONS = [
    ["01/04/25", "OPENING BALANCE", "", "", "", "", 45231.60],
    ["01/04/25", "UPI-SWIGGYINSTAMART-SWIGGY@YBL-YESB0000001-435820912-PAYMENT",
     "435820912", "01/04/25", 412.00, "", 44819.60],
    ["02/04/25", "SALARY CREDIT ACME TECHNOLOGIES PVT LTD",
     "NEFT0092331", "02/04/25", "", 85000.00, 129819.60],
    ["05/04/25", "UPI-NETFLIXINDIA-NETFLIX@ICICI-ICIC0000103-508812277-SUBSCRIPTION",
     "508812277", "05/04/25", 649.00, "", 129170.60],
    ["07/04/25", "UPI-MYNTRADESIGNS-MYNTRA@AXISBANK-UTIB0000441-509912834-ORDER",
     "509912834", "07/04/25", 2499.00, "", 126671.60],
    ["12/04/25", "ACH D- HOUSING RENT SHOBHA APARTMENTS",
     "ACH99120", "12/04/25", 28000.00, "", 98671.60],
    ["18/04/25", "UPI-MYNTRADESIGNS-MYNTRA@AXISBANK-UTIB0000441-511220945-REFUND",
     "511220945", "18/04/25", "", 2499.00, 101170.60],
    ["25/04/25", "ATM WDL BANNERGHATTA RD BLR",
     "ATM77213", "25/04/25", 5000.00, "", 96170.60],
]

DIVIDER = ["*" * 8, "*" * 34, "*" * 12, "*" * 8, "*" * 18, "*" * 18, "*" * 18]

#: Labels sit above their values, in matching columns.
SUMMARY_LABELS = ["Opening Balance", "", "", "", "Debits", "Credits", "Closing Bal"]
SUMMARY_VALUES = [45231.60, "", "", "", 36560.00, 87499.00, 96170.60]


def build(target: Path) -> None:
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Statement"

    for row in (
        ["HDFC BANK LIMITED"],
        ["Statement of account"],
        ["Account No: XXXXXXXX4471"],
        [],
        HEADER,
        DIVIDER,
        *TRANSACTIONS,
        DIVIDER,
        [],
        ["STATEMENT SUMMARY :-"],
        SUMMARY_LABELS,
        SUMMARY_VALUES,
        [],
        ["Dr Count", "", "", "", "Cr Count"],
        [5, "", "", "", 2],
        ["Generated On:", "10-Aug-2026 18:00", "Generated By:", "NET"],
    ):
        sheet.append(row)

    workbook.save(target)
    print(f"wrote {target}")


if __name__ == "__main__":
    FIXTURES.mkdir(parents=True, exist_ok=True)
    # Deliberately the wrong extension: this is how banks ship it.
    build(FIXTURES / "hdfc_april_2025.xls")
